export const tracks = [
  {
    title: 'Phonk',
    producer: 'Zaion',
    genre: 'funk',
    folder: 'phonk',
    BPM: 125,
    route: 'Phonk',
    opusSize: '750 KB',
    wavSize: '9.36 MB',
    tick: '1m',
    groupParams: {
      group1: { name: 'drums', color: '#f6f47b' },
      group2: { name: 'bass', color: '#192f95' },
      group3: { name: 'melody', color: '#0a9c8f' },
      group4: { name: 'chords', color: '#9b52aa' },
    },
  },
  {
    title: 'RevPhonk',
    producer: 'Noiaz',
    genre: 'phunk',
    folder: 'revPhonk',
    BPM: 125,
    route: 'Rev-phonk',
    opusSize: 1,
    wavSize: 2,
    tick: '4m',
    groupParams: {
      group1: { name: 'you', color: 'pink' },
      group2: { name: 'are', color: 'purple' },
      group3: { name: 'so', color: 'magenta' },
      group4: { name: 'weird', color: 'red' },
    },
  },
  {
    title: 'Layers',
    producer: 'Zaion',
    genre: 'drum & bass',
    folder: 'layers',
    BPM: 172,
    route: 'layers',
    opusSize: 1,
    wavSize: 2,
    tick: '4m',
    groupParams: {
      group1: { name: 'drums', color: '#1a3046' },
      group2: { name: 'bass', color: '#6c99c7' },
      group3: { name: 'leads', color: '#700505' },
      group4: { name: 'counters', color: '#125457' },
    },
  },
];
