export const tracks = [
  {
    title: 'Phonk',
    producer: 'Zaion',
    genre: 'funk',
    folder: 'phonk',
    BPM: 125,
    route: 'Phonk',
    opusSize: '750 KB',
    wavSize: '9.36 MB',
    tick: '1m',
    groupParams: {
      group1: { name: 'drums', color: '#f6f47b' },
      group2: { name: 'bass', color: '#192f95' },
      group3: { name: 'melody', color: '#0a9c8f' },
      group4: { name: 'chords', color: '#9b52aa' },
    },
  },
  {
    title: 'Discovery',
    producer: 'Zaion',
    genre: 'drum & bass',
    folder: 'discovery',
    BPM: 172,
    route: 'Discovery',
    opusSize: '975 KB',
    wavSize: '11.0 MB',
    tick: '4m',
    groupParams: {
      group1: { name: 'drums', color: '#F5C069' },
      group2: { name: 'bass', color: '#5F4AEB' },
      group3: { name: 'leads', color: 'magenta' },
      group4: { name: 'counters', color: '#1AC7F5' },
    },
  },
];
